shell = "zsh"

[templates]
defer = '''
    {{- hooks?.pre | nl }}
    {%- for file in files %}zsh-defer source "{{ file }}"{{ "\n" }}
    {%- endfor %}
    {{- hooks?.post | nl }}'''

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.prezto-spectrum]
remote = "https://raw.githubusercontent.com/sorin-ionescu/prezto/refs/heads/master/modules/spectrum/init.zsh"
apply = ["defer"]

[plugins.pure]
github = "sindresorhus/pure"
apply = ["fpath"]

# [plugins.zsh-abbr]
# github = "olets/zsh-abbr"
